version: "3.8"

name: 'yrp-api'
services:
  app:
    container_name: yrp-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - ${PORT}:3000
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - '.:/app'
      - '/app/node_modules'
