---
version: "3.8"

name: 'yrp-api'
volumes:
  yrp-pg-data:

services:
  app:
    container_name: yrp-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: yarn dev
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    volumes:
      - .:/app
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: yrp-api_development

  db:
    container_name: yrp-db
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yrp-api_development
    volumes:
      - yrp-pg-data:/var/lib/postgresql/data
